# Configuration file rendering for reticulum-go.
#
# Flat key = value format with [Section] headers.
{ lib }:

let
  renderInterface = name: iface:
    let
      optLine = key: value:
        if value == null then ""
        else "${key} = ${toString value}";
      lines = lib.filter (l: l != "") [
        (optLine "type" iface.type)
        (optLine "enabled" (lib.boolToString iface.enabled))
        (optLine "address" iface.address)
        (optLine "port" iface.port)
        (optLine "target_host" iface.target_host)
        (optLine "target_port" iface.target_port)
        (optLine "discovery_port" iface.discovery_port)
        (optLine "data_port" iface.data_port)
        (optLine "discovery_scope" iface.discovery_scope)
        (optLine "group_id" iface.group_id)
      ];
    in
      "[${name}]\n" + lib.concatStringsSep "\n" lines;

  mkConfigFile = { pkgs, cfg }:
    pkgs.writeText "reticulum-go-config" ''
      # Reticulum-Go configuration (generated by NixOS)
      enable_transport = ${lib.boolToString cfg.enableTransport}
      share_instance = ${lib.boolToString cfg.shareInstance}
      shared_instance_port = ${toString cfg.sharedInstancePort}
      instance_control_port = ${toString cfg.instanceControlPort}
      panic_on_interface_error = ${lib.boolToString cfg.panicOnInterfaceError}
      loglevel = ${toString cfg.logLevel}

      ${lib.concatStringsSep "\n\n" (lib.mapAttrsToList renderInterface cfg.interfaces)}
    '';

in {
  inherit renderInterface mkConfigFile;
}
