# Configuration file rendering for rnsd (Python reference implementation).
#
# Python-style booleans (True/False), TOML-ish [[subsection]] headers.
{ lib }:

let
  pyBool = b: if b then "True" else "False";

  renderInterface = name: iface:
    let
      optLine = key: value:
        if value == null then ""
        else "    ${key} = ${toString value}";

      commonLines = [
        (optLine "type" iface.type)
        (optLine "interface_enabled" (pyBool iface.enabled))
      ];

      typeLines =
        if iface.type == "UDPInterface" then
          let
            parts = lib.splitString ":" (if iface.address != null then iface.address else "");
            hasColon = iface.address != null && builtins.length parts == 2;
            listenIp = if hasColon then builtins.elemAt parts 0 else iface.address;
            listenPort = if hasColon then builtins.elemAt parts 1
                         else if iface.port != null then toString iface.port
                         else null;
            forwardIp = if listenIp == "0.0.0.0" then "255.255.255.255" else listenIp;
          in [
            (optLine "listen_ip" listenIp)
            (optLine "listen_port" listenPort)
            (optLine "forward_ip" forwardIp)
            (optLine "forward_port" listenPort)
          ]
        else if iface.type == "TCPClientInterface" then [
          (optLine "target_host" iface.target_host)
          (optLine "target_port" iface.target_port)
        ]
        else if iface.type == "AutoInterface" then [
          (optLine "group_id" iface.group_id)
          (optLine "discovery_scope" iface.discovery_scope)
          (optLine "discovery_port" iface.discovery_port)
          (optLine "data_port" iface.data_port)
        ]
        else [
          (optLine "address" iface.address)
          (optLine "port" iface.port)
          (optLine "target_host" iface.target_host)
          (optLine "target_port" iface.target_port)
          (optLine "discovery_port" iface.discovery_port)
          (optLine "data_port" iface.data_port)
          (optLine "discovery_scope" iface.discovery_scope)
          (optLine "group_id" iface.group_id)
        ];

      lines = lib.filter (l: l != "") (commonLines ++ typeLines);
    in
      "  [[${name}]]\n" + lib.concatStringsSep "\n" lines;

  mkConfigFile = { pkgs, cfg }:
    pkgs.writeText "rnsd-config" ''
# Reticulum configuration (generated by NixOS — rnsd module)

[reticulum]
enable_transport = ${pyBool cfg.enableTransport}
share_instance = ${pyBool cfg.shareInstance}
shared_instance_port = ${toString cfg.sharedInstancePort}
instance_control_port = ${toString cfg.instanceControlPort}
panic_on_interface_error = ${pyBool cfg.panicOnInterfaceError}

[logging]
loglevel = ${toString cfg.logLevel}

[interfaces]

${lib.concatStringsSep "\n\n" (lib.mapAttrsToList renderInterface cfg.interfaces)}
    '';

in {
  inherit pyBool renderInterface mkConfigFile;
}
